### ISSUE TITLE
Some dynamically loaded DOM elements are broken

### ISSUE THREAD

**Issue by wsdfhjxc** [wsdfhjxc/expose-noisy-tabs#14]
For example, this happens [here](http://www.texbiker.net/blog/), in the lower section containing embedded iframes with tweets.

**Comment by adisib** [comment]
If pages don't like to have elements appended to the body at all, then I would propose the following change. Keep appending the elements to a custom div as I had done, but don't append that div to the body. Instead, have the function that retrieves media elements through querySelectorAll calls to also retrieve elements from that div if it exists. That is probably the simplest thing to do here.

I will not be able to use the internet for about a week after this comment. If you haven't pushed a fix in that time I will make sure it gets fixed when I can.

**Comment by wsdfhjxc** [comment]
Seems to work correctly with 7564972.

**Comment by adisib** [comment]
I wasn't sure if appending to the documentElement would work, since I've heard that some browsers will take elements outside of head and body tags and move them into the body, possibly because the HTML implementation doesn't like having things there (because nothing is ever supposed to be there).

I was able to start testing today, so I was going to test your change as well as alternative solutions. Those alternative solutions seemed like they would be messy, due to having to get around the sandbox. So if this works, it is by far the simplest way.

**Comment by wsdfhjxc** [comment]
I guess this will still break some websites, so any alternative solutions are welcome :)
