### ISSUE TITLE
conflict with Overdrive e-reader

### ISSUE THREAD

**Issue by sunwapta** [wsdfhjxc/expose-noisy-tabs#22]
Found a conflict with [Overdrive](https://www.overdrive.com/) - a web-based e-reader for reading library ebooks. When your addon is enabled, and an e-book is selected to read, Overdrive attempts to launch, but gives only a completely blank page.  Disabling your addon, Overdrive works fine.

**Comment by adisib** [comment]
The addon is bothering the site's javascript code in a way that results in an error in the javascript's code. It is minified, so I can't see for sure why.

This is related to issue #14 . It doesn't like the addition of the script tag, no matter where it is placed, even if it is sitting safely isolated in the attach point (it doesn't mind the presence of the attach point itself). I assumed that other sites were using a query selector all with an nth child selector or something. But since this doesn't care where the script is placed, I'm not sure I want to know what kind of weird nonsense javascript the site is using.

The conflict with this site can easily be fixed by shoving it into an already existing script tag, with something like `let scriptAttach = document.getElementsByTagName("script")[0] || document.getElementById("ENTAttachPoint"); document.scriptAttach.appendChild(scriptInject);`. I don't want to do this, because although it would be weird for a site to yank out one of its script tags, it is less weird than what this website is currently doing. I think this easy fix would probably break more websites than it is helping.

**Comment by sunwapta** [comment]
Ok, thanks for the quick reply.
 Michael

**Comment by adisib** [comment]
Ok, I finally got the time to mess with this. I was actually being dumb with what I said before.

The fix is simple anyway. I will submit a pull request soon. It isn't a fix that will guarantee that other websites wont break for similar reasons, but I highly doubt any other websites should ever behave this weirdly, so I would consider the issue fixed for the next release, whenever that is.

**Comment by sunwapta** [comment]
Hey, that's great - thanks for looking into this - I find your addon really useful.
 Michael
