### ISSUE TITLE
Extension seems to "forget" mute state on page change/reload

### ISSUE THREAD

**Issue by pip25** [wsdfhjxc/expose-noisy-tabs#25]
Try muting a Youtube tab. Now press F5. The reloaded page will start playing with sound enabled. I think the intended behavior is to mute the tab itself, not just the particular page it is currently displaying. This can also happen if a page stops playing audio (not just pauses it), so the speaker icon disappears, then starts playing audio again a little later (for instance notification sounds).

**Comment by adisib** [comment]
The creator has been missing for a while. While I agree it would make more sense for it to mute tabs rather than documents, I'm not sure what the opinion of the creator is and we probably wont know for a while.

I've created a branch on my forked repository that will change the behavior to mute tabs so that mute stays when reloading a page or opening a new one. I wont do a pull request until I know if the creator wants this change, or to add an option that changes the behavior. You can find the modified version here:
https://github.com/adisib/expose-noisy-tabs/tree/mute-change

To install the modified version, first download it by clicking the green "Clone or Download" button on the page, and selecting "Download Zip". Then extract the zip and open the folder. Then build the extension by running the "build.cmd" file if you are on Windows (you will have to have 7-zip installed), or "build.sh" if you are on Linux or Mac. This will create a file with a ".xpi" extension. Simply open up the addon manager in Pale Moon, and drag the .xpi file into it.

Let me know if it works for you.

**Comment by pip25** [comment]
This works perfectly, thank you. :) The change itself is also much smaller than what I thought it would take.

**Comment by wsdfhjxc** [comment]
Thanks!
