### ISSUE TITLE
Extension floods console with errors

### ISSUE THREAD

**Issue by mrnhmath** [wsdfhjxc/expose-noisy-tabs#30]
Pale Moon 28.0.1
![capturar](https://user-images.githubusercontent.com/13562431/44923445-a1348d00-ad1e-11e8-8e12-11e2106fccc1.PNG)

**Comment by adisib** [comment]
Do you know if version 27.* had this issue?

If so, I seem to recall that at some point Firefox started firing the load-type events for ajax loads, and it is possible that it was pulled into version 28. In that case, fixing it might be as simple as changing the "
function onMediaElementEvent(event)" function to have a check that the element is a HTMLMediaElement, so that it would look like the following:
`
function onMediaElementEvent(event) {
    let mediaElement = event.target;
    let document = mediaElement.ownerDocument;
    let tab = findTabForDocument(document);

    if (tab.getAttribute(ENT_MUTED_ATTRIBUTE) === "true") {
        mediaElement.muted = true;
    }
    if (event.type === "loadstart" && mediaElement instanceof window.HTMLMediaElement && !tab.selected &&
        Prefs.getValue("preventAutoBackgroundPlayback")) {
        mediaElement.pause();
    } else {
        updateTabState(tab);
    }
}`

**Comment by mrnhmath** [comment]
@adisib Can't reproduce the issue with 27.9.4 Portable.
