### ISSUE TITLE
Icon not displayed when playing YouTube videos on Twitter and Facebook

### ISSUE THREAD

**Issue by xbeyond1** [wsdfhjxc/expose-noisy-tabs#5]
When I start a YouTube video on my Twitter and Facebook timelines, the icon does not display.

**Comment by wsdfhjxc** [comment]
Yes, currently there is a problem with some dynamically loaded media elements. I'll try to figure it out.

**Comment by adisib** [comment]
Embedded youtube videos use iframes. I would bet that iframes are the issue here. Greasemonkey injects into iframe documents by default; I don't know about extensions.

**Comment by wsdfhjxc** [comment]
Hmm, I should have thought of that before. This is already a terrible spaghetti and will be even worse. :laughing:

**Comment by wsdfhjxc** [comment]
Frame support seems to be working partially. There are still problems with some dynamically loaded frames, despite of plugging into them when capturing in `onDocumentLoad` method. Their `load` event is handled here as it is suggested on [MDN](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Tabbed_browser#Detecting_page_load). Sometimes it works, sometimes not. For those cases when it doesn't work, putting [these lines](https://github.com/wsdfhjxc/expose-noisy-tabs/blob/5dc3729683c4304d4bde23b0a7aba41e9fcdb863/bootstrap.js#L329-L330) into `setTimeout` makes it possible to plug into such a frame, but this should work without any stupid delays, because it's a `load` event.

**Comment by xbeyond1** [comment]
Soundcloud seems to have a problem as well.

**Comment by xbeyond1** [comment]
Periscope links don't work either on Twitter, but the icon does work on Periscope's own page.

**Comment by wsdfhjxc** [comment]
Can you try now?

**Comment by xbeyond1** [comment]
Awesome!

They all work now. :)

**Comment by wsdfhjxc** [comment]
That's good. I guess it's fine to close this now.
